package oy.sarjakuvat.flamingin.bde.algo

class MonominoLookup(val primeIndex: Int, val numRotations: Int = 0) {
    companion object {
        const val coalesceWithNeighbors = -1
        const val primeIndexShy = 0
        const val primeIndexU = 1
        const val primeIndexKnee = 5
        const val primeIndexL = 7
        const val primeIndexPipe = 17
        const val primeIndexT = 21
        const val primeIndexWSE = 23
        const val primeIndexWNE = 29
        const val primeIndexW = 31
        const val primeIndexCross = 85
        const val primeIndexInvThreeNE = 87
        const val primeIndexTwoNWSW = 95
        const val primeIndexTwoNWSE = 119
        const val primeIndexThreeNW = 127
        const val primeIndexImmersed = 0xff

        /* weird prerequisite for array literals */
        operator fun get(vararg array: Int) = array

        val primeTiles = this [0, 1, 5, 7, 17, 21, 23, 29, 31, 85, 87, 95, 119, 127, 0xff]

        /* the index is the neighbor configuration 8-bit mask */
        val seamLess = this [
            primeIndexShy,
            primeIndexShy,
            primeIndexU,
            primeIndexU,
            primeIndexShy,
            primeIndexShy,
            primeIndexU,
            primeIndexU,
            4,
            4,
            primeIndexKnee,
            primeIndexKnee,
            4,
            4,
            primeIndexL,
            primeIndexL,
            primeIndexShy,
            primeIndexShy,
            primeIndexU,
            primeIndexU,
            primeIndexShy,
            primeIndexShy,
            primeIndexU,
            primeIndexU,
            4,
            4,
            primeIndexKnee,
            primeIndexKnee,
            4,
            4,
            primeIndexL,
            primeIndexL,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            28,
            28,
            primeIndexT,
            primeIndexT,
            20,
            20,
            23,
            23,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            20,
            20,
            29,
            29,
            20,
            20,
            primeIndexW,
            primeIndexW,
            primeIndexShy,
            primeIndexShy,
            16,
            16,
            primeIndexShy,
            primeIndexShy,
            16,
            16,
            4,
            4,
            primeIndexKnee,
            primeIndexKnee,
            4,
            4,
            primeIndexL,
            primeIndexL,
            primeIndexShy,
            primeIndexShy,
            primeIndexU,
            primeIndexU,
            primeIndexShy,
            primeIndexShy,
            primeIndexU,
            primeIndexU,
            4,
            4,
            primeIndexKnee,
            primeIndexKnee,
            4,
            4,
            primeIndexL,
            primeIndexL,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            28,
            28,
            primeIndexT,
            primeIndexT,
            28,
            28,
            23,
            23,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            16,
            16,
            primeIndexPipe,
            primeIndexPipe,
            20,
            20,
            29,
            29,
            20,
            20,
            primeIndexW,
            primeIndexW,
            64,
            64,
            65,
            65,
            64,
            64,
            65,
            65,
            68,
            68,
            MonominoIndex.noice,
            197,
            68,
            68,
            71,
            199,
            64,
            64,
            65,
            65,
            64,
            64,
            65,
            65,
            68,
            68,
            MonominoIndex.noice,
            197,
            68,
            68,
            71,
            199,
            80,
            80,
            81,
            209,
            80,
            80,
            81,
            209,
            84,
            84,
            primeIndexCross,
            213,
            84,
            84,
            primeIndexInvThreeNE,
            215,
            80,
            80,
            81,
            209,
            80,
            80,
            81,
            209,
            92,
            92,
            93,
            primeIndexTwoNWSE,
            92,
            92,
            primeIndexTwoNWSW,
            223,
            64,
            64,
            65,
            65,
            64,
            64,
            65,
            65,
            68,
            68,
            MonominoIndex.noice,
            197,
            68,
            68,
            71,
            199,
            64,
            64,
            65,
            65,
            64,
            64,
            65,
            65,
            68,
            68,
            MonominoIndex.noice,
            197,
            68,
            68,
            71,
            199,
            80,
            80,
            113,
            241,
            80,
            80,
            113,
            241,
            116,
            116,
            117,
            245,
            116,
            116,
            primeIndexTwoNWSE,
            247,
            80,
            80,
            113,
            241,
            80,
            80,
            113,
            241,
            124,
            124,
            125,
            253,
            124,
            124,
            primeIndexThreeNW,
            primeIndexImmersed
        ]

        /* the clumsy pack as a whole */
        val clumsyPack = listOf(
            this [0, 4, 92, 124, 116, 80, 0],
            this [16, 20, 87, 223, 241, 21, 64],
            this [29, 117, 85, 71, 221, 125, 112],
            this [31, 253, 113, 28, 127, 247, 209],
            this [23, 199, 213, 95, 255, 245, 81],
            this [5, 84, 93, 119, 215, 193, 17],
            this [0, 1, 7, 197, MonominoIndex.noice, 68, 65]
        )
    }
}
